baseURL: http://stopify.fr/
title: Stopify
theme: bigspring
defaultContentLanguage: fr
paginate: 3
summaryLength: 15

deployment:
  targets:
    name: aws_s3
    URL: http://stopify-20210716084324996400000001.s3-website.eu-west-3.amazonaws.com

