name: github pages + aws-s3

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job_gh-pages:
    deploy:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true  # Fetch Hugo themes (true OR recursive)
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.85.0'
            extended: true

        - name: Build
          run: hugo --minify -e gh-pages -s website

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: github.ref == 'refs/heads/main'
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./website/public

  job_aws-s3:
    deploy:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true  # Fetch Hugo themes (true OR recursive)
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.85.0'
            extended: true

        - name: Build
          run: hugo --minify

        - name: Deploy
          run: hugo deploy --target=aws_s3 --configdir=/themes/bigspring/
          env:
            aws_region: 'eu-west-3'
            aws_s3_access: ${{ secrets.AWS_S3_ACCESS}}
            aws_s3_secret: ${{ secrets.AWS_S3_SECRET }}